turtlebot3: #namespace

    n_actions: 4 # We have 4 actions, Forwards,TurnLeft,TurnRight,Stop
    n_observations: 6 # We have 6 different observations

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 0.5 #0.3 # Speed for going fowards
    linear_turn_speed: 0.05 # Linear speed when turning
    angular_speed: 0.5 #0.3 # Angular speed when turning Left or Right
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    new_ranges: 5 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.3 # Minimum meters below wich we consider we have crashed
    max_laser_value: 6 # Value considered okay, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed
    max_linear_aceleration: 10.0 #5.0 # Linear acceleration value in which we consider Turtlebot 3 has crashed into something
    
    forwards_reward: 5 # Points Given to go forwards
    turn_reward: 1 # Points Given to turn as action
    end_episode_points: 1 # Points given when ending an episode
    
    step_size: 0.5 # By how many metres to move the robot at each step (in x or y direction)
    pedestrian_comfort_zone: 1.0 # radius around humans within which to penalize the state

    desired_pose:
      x: 5.0 #10.0
      y: 0.0
      z: 0.0